name: "Run Every Day At 20:02"

on:
  schedule:
  - cron: '0 03 * * *'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: mr-smithers-excellent/docker-build-push@v1.0
      with:
        image: debiansys/glghproxy
        tag: latest
        registry: docker.io
        dockerfile: Dockerfile
        username: debiansys
        password: ${{ secrets.DOCKER_PASSWORD }}
